accepted = [
    "Apache-2.0",
    "MIT",
    "ISC",
    "MPL-2.0",
    "BSD-3-Clause",
    "OpenSSL",
    "Unicode-DFS-2016",
]

workarounds = [
    "ring",
    "rustls",
]

[rustls-webpki.clarify]
license = "BSD-3-Clause AND ISC"

[[rustls-webpki.clarify.files]]
path = "LICENSE"
license = "ISC"
checksum = "5b698ca13897be3afdb7174256fa1574f8c6892b8bea1a66dd6469d3fe27885a"

[[rustls-webpki.clarify.files]]
path = "third-party/chromium/LICENSE"
license = "BSD-3-Clause"
checksum = "845022e0c1db1abb41a6ba4cd3c4b674ec290f3359d9d3c78ae558d4c0ed9308"

[webpki.clarify]
license = "BSD-3-Clause AND ISC"

[[webpki.clarify.files]]
path = "LICENSE"
license = "ISC"
checksum = "5b698ca13897be3afdb7174256fa1574f8c6892b8bea1a66dd6469d3fe27885a"

[[webpki.clarify.files]]
path = "third-party/chromium/LICENSE"
license = "BSD-3-Clause"
checksum = "845022e0c1db1abb41a6ba4cd3c4b674ec290f3359d9d3c78ae558d4c0ed9308"

